# Generated by Django 5.2.7 on 2025-11-25 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_alter_manga_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='images/sinfondo.png', upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Cuéntanos algo sobre ti', max_length=500)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='catalogo.manga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
