# Generated by Django 5.2.7 on 2025-10-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='stock',
        ),
    ]
