# Generated by Django 5.2.7 on 2025-10-25 16:26

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_manga_precio_remove_manga_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente si se deja vacío)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Sinopsis o descripción'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapter_number', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (ej: capitulo-1)', max_length=255)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalogo.manga')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('manga', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalogo.models.Panel.get_upload_path)),
                ('page_number', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='catalogo.chapter')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
