# Generated by Django 5.2.7 on 2025-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_manga_slug_alter_manga_descripcion_chapter_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Sinopsis'),
        ),
    ]
