# Generated by Django 5.2.7 on 2025-11-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_manga_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='page_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Arco')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='catalogo.manga')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('manga', 'title')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='arc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='catalogo.arc'),
        ),
    ]
