# Generated by Django 5.2.7 on 2025-11-27 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_manga_owner_alter_chapter_slug_alter_manga_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['order'], 'verbose_name': 'Arco', 'verbose_name_plural': 'Arcos'},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['titulo'], 'verbose_name': 'Manga', 'verbose_name_plural': 'Mangas'},
        ),
        migrations.AlterUniqueTogether(
            name='arc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arc',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden de Lectura'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='arc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='catalogo.arc', verbose_name='Arco'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título del Capítulo'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve descripción de la trama.', verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manga',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Portada Oficial'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para URLs.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='page_number',
            field=models.PositiveIntegerField(verbose_name='Número de Página'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('manga', 'chapter_number')},
        ),
    ]
