# Generated by Django 5.2.7 on 2025-11-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_arc_options_alter_manga_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='manga',
            name='genero',
            field=models.CharField(choices=[('shonen', 'Shonen'), ('seinen', 'Seinen'), ('shojo', 'Shojo'), ('josei', 'Josei'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('slice_of_life', 'Slice of Life'), ('terror', 'Terror')], default='shonen', max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='arc',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='arc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='catalogo.arc'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='panel',
            name='page_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='arc',
            unique_together={('manga', 'title')},
        ),
    ]
