# Generated by Django 5.2.7 on 2025-11-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_arc_options_manga_genero_alter_arc_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['order'], 'verbose_name': 'Arco', 'verbose_name_plural': 'Arcos'},
        ),
        migrations.AlterUniqueTogether(
            name='arc',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='arc',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden de Lectura'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='arc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='catalogo.arc', verbose_name='Arco'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título del Capítulo'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genero',
            field=models.CharField(choices=[('shonen', 'Shonen'), ('seinen', 'Seinen'), ('shojo', 'Shojo'), ('josei', 'Josei'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('slice_of_life', 'Slice of Life'), ('terror', 'Terror'), ('accion', 'Acción'), ('aventura', 'Aventura'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('fantasia', 'Fantasía'), ('misterio', 'Misterio'), ('psicologico', 'Psicológico'), ('romance', 'Romance'), ('sci_fi', 'Ciencia Ficción'), ('deportes', 'Deportes')], default='shonen', help_text='Categoría principal del manga', max_length=50, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='page_number',
            field=models.PositiveIntegerField(verbose_name='Número de Página'),
        ),
    ]
